window.KB_SETUP=function(){
const {ref,computed}=Vue
const mobile=ref(false),tab=ref('home'),page=ref('workbench'),modal=ref(''),toast=ref(''),query=ref(''),selected=ref(null)
const nav=[['workbench','solar:widget-5-linear','我的工作台'],['enterprise','solar:buildings-2-linear','企业空间'],['personal','solar:user-circle-linear','个人空间'],['collab','solar:users-group-rounded-linear','协作空间'],['related','solar:link-circle-linear','与我相关'],['links','solar:link-round-linear','安全外链'],['recycle','solar:trash-bin-trash-linear','误删恢复'],['search','solar:magnifer-linear','全局搜索'],['messages','solar:bell-linear','消息中心']]
const admin=[['dept','solar:buildings-linear','部门管理'],['member','solar:users-group-two-rounded-linear','成员管理'],['admin','solar:shield-user-linear','管理员设置'],['stats','solar:chart-square-linear','空间统计']]
const meta={workbench:['我的工作台','聚合空间、文件和待办事项'],enterprise:['企业空间','组织资产与部门资料库'],personal:['个人空间','本人私有工作文件区'],collab:['协作空间','集团内部跨部门协作'],related:['与我相关','共享、审批和收集关系'],links:['安全外链','对外分发与访问控制'],recycle:['误删恢复','软删除、恢复与彻底清理'],search:['全局搜索','跨空间检索知识内容'],messages:['消息中心','协作、审批与安全通知'],dept:['部门管理','组织树、资料库与默认权限'],member:['成员管理','部门归属、状态和资产交接'],admin:['管理员设置','管理范围与功能授权'],stats:['空间统计','容量、活跃和安全态势']}
const files=ref([{name:'2026年度重点工作计划.docx',kind:'doc',space:'企业空间',size:'2.8 MB',time:'今天 10:26'},{name:'智能知识库建设项目',kind:'folder',space:'企业空间',size:'12 项',time:'今天 09:42'},{name:'安全服务管控清单.xlsx',kind:'sheet',space:'企业空间',size:'1.4 MB',time:'昨天 16:18'},{name:'平台交付验收标准.pdf',kind:'pdf',space:'个人空间',size:'8.7 MB',time:'昨天 14:07'}])
const datasets={collab:[['智能知识库建设项目','12 位成员 · 286 个文件','进行中'],['集团安全专项整改','8 位成员 · 74 个文件','进行中'],['数据治理联合工作组','16 位成员 · 152 个文件','已归档']],related:[['共享给我的项目资料','王琳共享 · 可预览','共享资源'],['下载权限申请','数字中心资料库','待我审批'],['项目周报收集','截止 6 月 28 日','待提交']],links:[['平台交付验收标准.pdf','预览、下载 · 7 天','36 次访问'],['集团安全培训材料','仅预览 · 永久','128 次访问'],['项目周报模板.docx','已失效','9 次访问']],recycle:[['旧版部署方案.docx','企业空间 / 数字中心','今天 08:15'],['接口测试截图','个人空间','昨天 18:22'],['历史项目资料.zip','协作空间','6 月 21 日']],dept:[['数字中心','86 位成员 · 1.42 TB','默认权限：下载者'],['安全管理部','42 位成员 · 680 GB','默认权限：预览者'],['综合管理部','35 位成员 · 320 GB','默认权限：下载者']],member:[['王琳','数字中心 · 部门负责人','正常'],['夏寿好','数字中心 · 技术开发岗','正常'],['李晨','安全管理部 · 文件管理员','正常'],['陈卓','项目管理中心 · 项目经理','正常']],admin:[['王琳','全集团','系统管理员'],['李晨','数字中心及下级','分级管理员'],['周颖','安全管理部及下级','分级管理员']],search:[['知识库建设方案.docx','企业空间 / 数字中心','文档'],['夏寿好','数字中心 / 技术开发岗','成员'],['接口联调知识条目','协作空间','知识内容']],messages:[['权限申请待审批','数字中心资料库','刚刚'],['文件收集即将到期','项目周报收集','10 分钟前'],['外链访问风险提醒','来自异常 IP','1 小时前']],stats:[['空间总量','2.48 TB','较上月 +8.2%'],['今日活跃','628 人','活跃率 74%'],['文件访问','18.6k 次','高峰 10:00'],['安全事件','3 项','均已处置']]}
const title=computed(()=>meta[page.value]||['智汇知识库','']),filtered=computed(()=>files.value.filter(f=>f.name.includes(query.value))),rows=computed(()=>datasets[page.value]||[])
function go(p){page.value=p;query.value='';scrollTo(0,0)}function note(x){toast.value=x;setTimeout(()=>toast.value='',1700)}function open(x,item=null){modal.value=x;selected.value=item}function icon(k){return k==='folder'?'solar:folder-with-files-bold-duotone':k==='sheet'?'vscode-icons:file-type-excel':k==='pdf'?'vscode-icons:file-type-pdf2':'vscode-icons:file-type-word'}function add(){files.value.unshift({name:modal.value==='folder'?'新建文件夹':'新上传的项目材料.pdf',kind:modal.value==='folder'?'folder':'pdf',space:page.value==='personal'?'个人空间':'企业空间',size:modal.value==='folder'?'0 项':'4.2 MB',time:'刚刚'});modal.value='';note('操作已完成')}
return{mobile,tab,page,modal,toast,query,selected,nav,admin,title,files,filtered,rows,datasets,go,note,open,icon,add}}
